wandb_version: 1

pretrain:
  desc: null
  value: /storage5/hf_private/model/hatakeyama-llm-team/Tanuki-8B-Instruct-without-DPO
ref_pretrain:
  desc: null
  value: /storage5/hf_private/model/hatakeyama-llm-team/Tanuki-8B-Instruct-without-DPO
dataset:
  desc: null
  value: Anthropic/hh-rlhf,tasksource/oasst1_pairwise_rlhf_reward,openai/webgpt_comparisons
dataset_probs:
  desc: null
  value: 0.72,0.08,0.2
save_path:
  desc: null
  value: ./ckpt/7b_llama
save_steps:
  desc: null
  value: -1
logging_steps:
  desc: null
  value: 1
eval_steps:
  desc: null
  value: -1
ckpt_path:
  desc: null
  value: ./ckpt/checkpoints_dpo
max_ckpt_num:
  desc: null
  value: 3
max_ckpt_mem:
  desc: null
  value: 1000
max_epochs:
  desc: null
  value: 1
micro_train_batch_size:
  desc: null
  value: 1
train_batch_size:
  desc: null
  value: 128
load_checkpoint:
  desc: null
  value: false
max_norm:
  desc: null
  value: 1.0
max_len:
  desc: null
  value: 2048
l2:
  desc: null
  value: 0.0
beta:
  desc: null
  value: 0.1
ipo:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
gradient_checkpointing:
  desc: null
  value: true
seed:
  desc: null
  value: 42
disable_fast_tokenizer:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
zero_stage:
  desc: null
  value: 3
bf16:
  desc: null
  value: true
ref_offload:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 5.0e-07
zpg:
  desc: null
  value: 1
adam_offload:
  desc: null
  value: false
flash_attn:
  desc: null
  value: true
max_samples:
  desc: null
  value: 1000000
aux_loss_coef:
  desc: null
  value: 0
grad_accum_dtype:
  desc: null
  value: null
disable_trace_cache:
  desc: null
  value: false
load_in_4bit:
  desc: null
  value: false
lora_rank:
  desc: null
  value: 8
lora_alpha:
  desc: null
  value: 16
target_modules:
  desc: null
  value: all-linear
lora_dropout:
  desc: null
  value: 0.05
gradient_checkpointing_use_reentrant:
  desc: null
  value: false
prompt_key:
  desc: null
  value: null
chosen_key:
  desc: null
  value: null
rejected_key:
  desc: null
  value: null
input_template:
  desc: null
  value: 'Human: {}

    Assistant: '
apply_chat_template:
  desc: null
  value: false
use_wandb:
  desc: null
  value: 'true'
wandb_org:
  desc: null
  value: weblab-geniac1
wandb_group:
  desc: null
  value: test
wandb_project:
  desc: null
  value: OpenRLHF-test
wandb_run_name:
  desc: null
  value: test
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.3
    framework: huggingface
    huggingface_version: 4.41.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719491740
    t:
      1:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      - 98
      2:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      - 98
      3:
      - 7
      - 13
      - 16
      - 23
      - 66
      4: 3.10.14
      5: 0.17.3
      6: 4.41.0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: eval/global_step
      6:
      - 3
    - 1: train/preference_loss
      5: 1
      6:
      - 1
    - 1: train/chosen_reward
      5: 1
      6:
      - 1
    - 1: train/reject_reward
      5: 1
      6:
      - 1
    - 1: train/acc_mean
      5: 1
      6:
      - 1
    - 1: train/loss_mean
      5: 1
      6:
      - 1
